// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {IndexioShareTokenV3} from "./IndexioShareTokenV3.sol";import {IndexioIncomeHubV3} from "./IndexioIncomeHubV3.sol";import {IndexioGovernorV3} from "./IndexioGovernorV3.sol";
interface IFactoryV3 {function registry() external view returns(address);function feeTreasury() external view returns(address);function safetyController() external view returns(address);function settlementToken() external view returns(address);}interface IRegistryCheckV3{function requireAsset(address,uint16) external view returns(uint8);}interface ISafetyV3{function depositsPaused(address) external view returns(bool);function tradingPaused(address) external view returns(bool);}
contract IndexioVaultV3 is ReentrancyGuard {using SafeERC20 for IERC20;uint16 constant BPS=10_000;uint16 public constant INDEXIO_FEE_BPS=100;address public immutable factory;address public immutable creator;IndexioShareTokenV3 public immutable shareToken;IndexioIncomeHubV3 public immutable incomeHub;IndexioGovernorV3 public immutable governor;uint16 public creatorFeeBps;address[] private _assets;uint16[] private _weights;
event Deposited(address indexed caller,address indexed receiver,uint256 shares);event Redeemed(address indexed owner,address indexed receiver,uint256 shares);event CreatorFeeUpdated(uint16 oldFee,uint16 newFee);event CompositionUpdated(address[] assets,uint16[] weights);
constructor(address f,address c,string memory n,string memory s,address[] memory a,uint16[] memory w,uint16 cf,uint16 reward){require(f.code.length>0&&c!=address(0)&&cf<=100,"config");factory=f;creator=c;creatorFeeBps=cf;_validate(a,w);_assets=a;_weights=w;shareToken=new IndexioShareTokenV3(n,s,address(this));incomeHub=new IndexioIncomeHubV3(address(this),address(shareToken),c,reward);shareToken.setIncomeHub(address(incomeHub));governor=new IndexioGovernorV3(address(this),address(shareToken));}
function assets() external view returns(address[] memory){return _assets;}function weights() external view returns(uint16[] memory){return _weights;}
function deposit(uint256[] calldata gross,address receiver) external nonReentrant returns(uint256 shares){require(!ISafetyV3(IFactoryV3(factory).safetyController()).depositsPaused(address(this)),"paused");require(receiver!=address(0)&&gross.length==_assets.length,"input");_validate(_assets,_weights);uint256 supply=shareToken.totalSupply();uint256 minShares=type(uint256).max;uint256 feeBps=INDEXIO_FEE_BPS+creatorFeeBps;for(uint256 i;i<_assets.length;i++){require(gross[i]>0,"zero");uint256 net=gross[i]*(BPS-feeBps)/BPS;if(supply>0){uint256 bal=IERC20(_assets[i]).balanceOf(address(this));require(bal>0,"empty asset");minShares=Math.min(minShares,Math.mulDiv(net,supply,bal));}}if(supply==0){require(msg.sender==creator,"initial creator");shares=_initialShares(gross,feeBps);}else{shares=minShares;}require(shares>0,"shares");address treasury=IFactoryV3(factory).feeTreasury();for(uint256 i;i<_assets.length;i++){uint256 protocolFee=gross[i]*INDEXIO_FEE_BPS/BPS;uint256 creatorFee=gross[i]*creatorFeeBps/BPS;uint256 net=gross[i]-protocolFee-creatorFee;if(supply>0){uint256 requiredNet=Math.mulDiv(IERC20(_assets[i]).balanceOf(address(this)),shares,supply,Math.Rounding.Ceil);require(net>=requiredNet,"ratio");net=requiredNet;}_pullExact(_assets[i],msg.sender,address(this),net);if(protocolFee>0)IERC20(_assets[i]).safeTransferFrom(msg.sender,treasury,protocolFee);if(creatorFee>0)IERC20(_assets[i]).safeTransferFrom(msg.sender,creator,creatorFee);}shareToken.mint(receiver,shares);emit Deposited(msg.sender,receiver,shares);}
function redeem(uint256 shares,address receiver) external nonReentrant returns(uint256[] memory amounts){require(shares>0&&receiver!=address(0),"input");uint256 supply=shareToken.totalSupply();require(shares<=shareToken.balanceOf(msg.sender),"shares");amounts=new uint256[](_assets.length);shareToken.burn(msg.sender,shares);address treasury=IFactoryV3(factory).feeTreasury();for(uint256 i;i<_assets.length;i++){uint256 gross=Math.mulDiv(IERC20(_assets[i]).balanceOf(address(this)),shares,supply);uint256 p=gross*INDEXIO_FEE_BPS/BPS;uint256 c=gross*creatorFeeBps/BPS;amounts[i]=gross-p-c;if(p>0)IERC20(_assets[i]).safeTransfer(treasury,p);if(c>0)IERC20(_assets[i]).safeTransfer(creator,c);IERC20(_assets[i]).safeTransfer(receiver,amounts[i]);}emit Redeemed(msg.sender,receiver,shares);}
function lowerCreatorFee(uint16 n) external {require(msg.sender==creator&&n<=creatorFeeBps,"fee");uint16 o=creatorFeeBps;creatorFeeBps=n;emit CreatorFeeUpdated(o,n);}function notifyIncome(address token) external {require(msg.sender==creator&&token.code.length>0,"creator/token");bool ok=token==IFactoryV3(factory).settlementToken();for(uint256 i;i<_assets.length&&!ok;i++)if(token==_assets[i])ok=true;require(ok,"unsupported income");incomeHub.notifyIncome(token);}
function executeGovernance(uint8 kind,address[] calldata a,uint16[] calldata w,uint16 nf) external {require(msg.sender==address(governor),"governor");require(!ISafetyV3(IFactoryV3(factory).safetyController()).tradingPaused(address(this)),"trading paused");if(kind==2){require(nf<=100&&nf>=creatorFeeBps,"fee");uint16 o=creatorFeeBps;creatorFeeBps=nf;emit CreatorFeeUpdated(o,nf);return;}_validate(a,w);if(kind==0){require(a.length==_assets.length,"assets");for(uint256 i;i<a.length;i++)require(a[i]==_assets[i],"rebalance assets");}else{for(uint256 i;i<_assets.length;i++){bool keep;for(uint256 j;j<a.length;j++)if(a[j]==_assets[i]){keep=true;break;}if(!keep)require(IERC20(_assets[i]).balanceOf(address(this))==0,"removed balance");}}_assets=a;_weights=w;emit CompositionUpdated(a,w);}
function _initialShares(uint256[] calldata gross,uint256 feeBps) internal view returns(uint256 shares){shares=type(uint256).max;address r=IFactoryV3(factory).registry();for(uint256 i;i<_assets.length;i++){uint8 d=IRegistryCheckV3(r).requireAsset(_assets[i],_weights[i]);uint256 net=gross[i]*(BPS-feeBps)/BPS;uint256 normalized=d<18?net*(10**(18-d)):net/(10**(d-18));shares=Math.min(shares,normalized);}require(shares>=1e6,"initial too small");}
function _pullExact(address token,address from,address to,uint256 amount) internal {uint256 beforeBal=IERC20(token).balanceOf(to);IERC20(token).safeTransferFrom(from,to,amount);require(IERC20(token).balanceOf(to)-beforeBal==amount,"nonstandard token");}
function _validate(address[] memory a,uint16[] memory w) internal view {require(a.length>0&&a.length==w.length&&a.length<=20,"composition");uint256 sum;address r=IFactoryV3(factory).registry();for(uint256 i;i<a.length;i++){IRegistryCheckV3(r).requireAsset(a[i],w[i]);sum+=w[i];for(uint256 j;j<i;j++)require(a[j]!=a[i],"duplicate");}require(sum==BPS,"weights");}
}
