// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
import {IndexioShareTokenV3} from "./IndexioShareTokenV3.sol";
interface IFactoryV3 { function registry() external view returns(address); function feeTreasury() external view returns(address); function safetyController() external view returns(address); function registerVault(address,address,uint16,uint16) external; }
interface IRegistryCheckV3 { function requireAsset(address,uint16) external view returns(uint8); }
interface ISafetyV3 { function depositsPaused(address) external view returns(bool); }
contract IndexioVaultV3 { using SafeERC20 for IERC20; uint16 public constant BPS=10_000; uint16 public constant INDEXIO_FEE_BPS=100;
    address public immutable factory; address public immutable creator; IndexioShareTokenV3 public immutable shareToken; uint16 public creatorFeeBps; address[] private _assets; uint16[] private _weights;
    event Deposited(address indexed caller,address indexed receiver,uint256 shares); event Redeemed(address indexed owner,address indexed receiver,uint256 shares); event CreatorFeeUpdated(uint16 oldFee,uint16 newFee);
    constructor(address factory_,address creator_,string memory name_,string memory symbol_,address[] memory assets_,uint16[] memory weights_,uint16 creatorFee_,uint16 incomeReward_){require(factory_!=address(0)&&creator_!=address(0)&&creatorFee_<=100,"config");factory=factory_;creator=creator_;_setComposition(assets_,weights_);shareToken=new IndexioShareTokenV3(name_,symbol_,address(this));creatorFeeBps=creatorFee_;IFactoryV3(factory_).registerVault(address(this),creator_,creatorFee_,incomeReward_);}
    function assets() external view returns(address[] memory){return _assets;} function weights() external view returns(uint16[] memory){return _weights;}
    function deposit(uint256[] calldata gross,address receiver) external returns(uint256 shares){require(!ISafetyV3(IFactoryV3(factory).safetyController()).depositsPaused(address(this)),"paused");require(receiver!=address(0)&&gross.length==_assets.length,"input");uint256 supply=shareToken.totalSupply();uint256 minRatio=type(uint256).max;address treasury=IFactoryV3(factory).feeTreasury();for(uint256 i;i<_assets.length;i++){uint256 fee=gross[i]*(INDEXIO_FEE_BPS+creatorFeeBps)/BPS;uint256 net=gross[i]-fee;uint256 bal=IERC20(_assets[i]).balanceOf(address(this));if(supply>0)minRatio=Math.min(minRatio,Math.mulDiv(net,supply,bal));IERC20(_assets[i]).safeTransferFrom(msg.sender,address(this),net);uint256 protocolFee=gross[i]*INDEXIO_FEE_BPS/BPS;if(protocolFee>0)IERC20(_assets[i]).safeTransferFrom(msg.sender,treasury,protocolFee);uint256 creatorFee=fee-protocolFee;if(creatorFee>0)IERC20(_assets[i]).safeTransferFrom(msg.sender,creator,creatorFee);}shares=supply==0?1e18:minRatio;require(shares>0,"shares");shareToken.mint(receiver,shares);emit Deposited(msg.sender,receiver,shares);}
    function redeem(uint256 shares,address receiver) external returns(uint256[] memory amounts){require(shares>0&&receiver!=address(0),"input");uint256 supply=shareToken.totalSupply();amounts=new uint256[](_assets.length);shareToken.burn(msg.sender,shares);address treasury=IFactoryV3(factory).feeTreasury();for(uint256 i;i<_assets.length;i++){uint256 gross=Math.mulDiv(IERC20(_assets[i]).balanceOf(address(this)),shares,supply);uint256 p=gross*INDEXIO_FEE_BPS/BPS;uint256 c=gross*creatorFeeBps/BPS;amounts[i]=gross-p-c;if(p>0)IERC20(_assets[i]).safeTransfer(treasury,p);if(c>0)IERC20(_assets[i]).safeTransfer(creator,c);IERC20(_assets[i]).safeTransfer(receiver,amounts[i]);}emit Redeemed(msg.sender,receiver,shares);}
    function lowerCreatorFee(uint16 newFee) external {require(msg.sender==creator&&newFee<=creatorFeeBps,"fee");uint16 old=creatorFeeBps;creatorFeeBps=newFee;emit CreatorFeeUpdated(old,newFee);} 
    function _setComposition(address[] memory a,uint16[] memory w) internal {require(a.length>0&&a.length==w.length&&a.length<=20,"composition");uint256 sum;address r=IFactoryV3(factory).registry();for(uint256 i;i<a.length;i++){IRegistryCheckV3(r).requireAsset(a[i],w[i]);sum+=w[i];for(uint256 j;j<i;j++)require(a[j]!=a[i],"duplicate");}require(sum==BPS,"weights");_assets=a;_weights=w;}
}
