// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
interface IShareBalanceV3 { function balanceOf(address) external view returns(uint256); function totalSupply() external view returns(uint256); }
contract IndexioIncomeHubV3 is ReentrancyGuard { using SafeERC20 for IERC20; uint256 constant SCALE=1e36; address public immutable vault; address public immutable shareToken; address public immutable creator; uint16 public immutable creatorIncomeRewardBps; address[] public incomeTokens; mapping(address=>bool) public known; mapping(address=>uint256) public accPerShare; mapping(address=>mapping(address=>uint256)) public debt; mapping(address=>mapping(address=>uint256)) public credit; mapping(address=>uint256) public accounted;
event IncomeNotified(address indexed token,uint256 received,uint256 creatorReward,uint256 distributable);event Claimed(address indexed account,address indexed token,address indexed receiver,uint256 amount);
constructor(address v,address s,address c,uint16 r){require(v!=address(0)&&s!=address(0)&&c!=address(0)&&r<=2000,"config");vault=v;shareToken=s;creator=c;creatorIncomeRewardBps=r;}
function notifyIncome(address token) external nonReentrant {require(msg.sender==vault,"vault");uint256 supply=IShareBalanceV3(shareToken).totalSupply();require(supply>0,"supply");uint256 bal=IERC20(token).balanceOf(address(this));require(bal>accounted[token],"income");uint256 received=bal-accounted[token];uint256 reward=received*creatorIncomeRewardBps/10_000;if(reward>0){IERC20(token).safeTransfer(creator,reward);bal-=reward;}uint256 d=received-reward;if(!known[token]){known[token]=true;incomeTokens.push(token);}accPerShare[token]+=d*SCALE/supply;accounted[token]=bal;emit IncomeNotified(token,received,reward,d);}
function syncTransfer(address from,address to,uint256 fromOld,uint256 fromNew,uint256 toOld,uint256 toNew) external {require(msg.sender==shareToken,"share");for(uint256 i;i<incomeTokens.length;i++){address t=incomeTokens[i];if(from!=address(0))_sync(t,from,fromOld,fromNew);if(to!=address(0)&&to!=from)_sync(t,to,toOld,toNew);}}
function _sync(address t,address a,uint256 oldBal,uint256 newBal) internal {uint256 x=accPerShare[t];uint256 accrued=oldBal*x/SCALE;uint256 prev=debt[t][a];if(accrued>prev)credit[t][a]+=accrued-prev;debt[t][a]=newBal*x/SCALE;}
function claim(address token,address receiver) external nonReentrant returns(uint256 amount){require(receiver!=address(0),"receiver");uint256 bal=IShareBalanceV3(shareToken).balanceOf(msg.sender);uint256 accrued=bal*accPerShare[token]/SCALE;uint256 prev=debt[token][msg.sender];amount=credit[token][msg.sender]+(accrued>prev?accrued-prev:0);credit[token][msg.sender]=0;debt[token][msg.sender]=accrued;if(amount>0){accounted[token]-=amount;IERC20(token).safeTransfer(receiver,amount);}emit Claimed(msg.sender,token,receiver,amount);}
function incomeTokenCount() external view returns(uint256){return incomeTokens.length;}
}
