// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {IERC721} from "@openzeppelin/contracts/token/ERC721/IERC721.sol";
import {IERC1155} from "@openzeppelin/contracts/token/ERC1155/IERC1155.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract TobyworldMarketplaceV1 is ReentrancyGuard {
    using SafeERC20 for IERC20;
    uint256 public constant BASE_CHAIN_ID = 8453;
    address public constant SEED = 0x02C97bfFEAe8406A3050C83185314B001D84b802;
    uint256 public constant SEED_TOKEN_ID = 1;
    address public constant OLD_LORE_LAND = 0x08f74Dd2913d7A7a4C7339B9106AE14654265b62;
    address public constant CANONICAL_LORE_LAND = 0x0495601Af6f86efb14C9D478eA46b2Aa09cB164A;
    address public constant USDC = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;
    address public constant TOBY = 0xb8D98a102b0079B69FFbc760C8d857A31653e56e;
    uint256 public constant FEE_BPS = 100;
    uint256 public constant BPS_DENOMINATOR = 10_000;
    address public constant INITIAL_FEE_RECIPIENT = 0x0ba4aB96AFfe0486DeB9a04B9dB53B0c1a65f2d8;
    enum AssetKind { SEED, OLD_LORE_LAND, CANONICAL_LORE_LAND }
    enum ListingStatus { NONE, ACTIVE, SOLD, CANCELLED }
    struct Listing { address seller; address paymentToken; uint256 tokenId; uint256 quantity; uint256 price; uint64 expiresAt; AssetKind assetKind; ListingStatus status; }
    uint256 public nextListingId = 1;
    mapping(uint256 => Listing) public listings;
    mapping(address => mapping(uint256 => uint256)) public activeLandListing;
    mapping(address => uint256) public reservedSeeds;
    address public feeRecipient;
    address public pendingFeeRecipient;
    event ListingCreated(uint256 indexed listingId,address indexed seller,AssetKind indexed assetKind,uint256 tokenId,uint256 quantity,address paymentToken,uint256 price,uint64 expiresAt);
    event ListingUpdated(uint256 indexed listingId,address paymentToken,uint256 price,uint64 expiresAt);
    event ListingCancelled(uint256 indexed listingId);
    event ListingPurchased(uint256 indexed listingId,address indexed seller,address indexed buyer,AssetKind assetKind,uint256 tokenId,uint256 quantity,address paymentToken,uint256 price,uint256 marketplaceFee);
    event FeeRecipientProposed(address indexed currentRecipient,address indexed proposedRecipient);
    event FeeRecipientChanged(address indexed previousRecipient,address indexed newRecipient);
    event FeeRecipientProposalCancelled(address indexed currentRecipient,address indexed cancelledRecipient);
    error WrongChain(uint256 chainId); error MissingContract(address target); error InvalidListing(); error ListingNotActive(); error NotSeller(); error SellerCannotBuy(); error ZeroPrice(); error ZeroQuantity(); error InvalidExpiry(); error UnsupportedPaymentToken(address token); error InvalidSeedTokenId(uint256 tokenId); error InvalidERC721Quantity(uint256 quantity); error AssetNotOwned(); error MarketplaceNotApproved(); error ERC721AlreadyListed(uint256 listingId); error InsufficientSeeds(uint256 available,uint256 requested); error ListingExpired(uint64 expiresAt); error ListingTermsChanged(); error WrongNativeValue(uint256 received,uint256 required); error UnexpectedNativeValue(); error NativeTransferFailed(address recipient); error InexactERC20Payment(); error InvalidFeeRecipient(); error NotFeeRecipient(); error NotPendingFeeRecipient();
    constructor(){ if(block.chainid!=BASE_CHAIN_ID) revert WrongChain(block.chainid); _requireContract(SEED); _requireContract(OLD_LORE_LAND); _requireContract(CANONICAL_LORE_LAND); _requireContract(USDC); _requireContract(TOBY); feeRecipient=INITIAL_FEE_RECIPIENT; }
    function createListing(AssetKind assetKind,uint256 tokenId,uint256 quantity,address paymentToken,uint256 price,uint64 expiresAt) external nonReentrant returns(uint256 listingId){ _validateTerms(paymentToken,price,expiresAt); if(assetKind==AssetKind.SEED){_validateNewSeedListing(msg.sender,tokenId,quantity);}else{address asset=assetAddress(assetKind);_clearStaleLandListing(asset,tokenId);_validateLand(asset,tokenId,quantity,msg.sender);} listingId=nextListingId;nextListingId=listingId+1; listings[listingId]=Listing(msg.sender,paymentToken,tokenId,quantity,price,expiresAt,assetKind,ListingStatus.ACTIVE); if(assetKind==AssetKind.SEED){reservedSeeds[msg.sender]+=quantity;}else{activeLandListing[assetAddress(assetKind)][tokenId]=listingId;} emit ListingCreated(listingId,msg.sender,assetKind,tokenId,quantity,paymentToken,price,expiresAt); }
    function updateListing(uint256 listingId,address paymentToken,uint256 price,uint64 expiresAt) external nonReentrant {Listing storage listing=listings[listingId];_requireActive(listing);if(listing.seller!=msg.sender)revert NotSeller();_validateTerms(paymentToken,price,expiresAt);_validateListingAsset(listing);listing.paymentToken=paymentToken;listing.price=price;listing.expiresAt=expiresAt;emit ListingUpdated(listingId,paymentToken,price,expiresAt);}
    function cancelListing(uint256 listingId) external nonReentrant {Listing storage listing=listings[listingId];_requireActive(listing);if(listing.seller!=msg.sender)revert NotSeller();listing.status=ListingStatus.CANCELLED;_releaseListing(listingId,listing);emit ListingCancelled(listingId);}
    function buy(uint256 listingId,address expectedPaymentToken,uint256 expectedPrice) external payable nonReentrant {Listing storage listing=listings[listingId];_requireActive(listing);if(listing.expiresAt!=0&&block.timestamp>listing.expiresAt)revert ListingExpired(listing.expiresAt);if(msg.sender==listing.seller)revert SellerCannotBuy();if(listing.paymentToken!=expectedPaymentToken||listing.price!=expectedPrice)revert ListingTermsChanged();_validateListingAsset(listing);address seller=listing.seller;address paymentToken=listing.paymentToken;uint256 price=listing.price;uint256 tokenId=listing.tokenId;uint256 quantity=listing.quantity;AssetKind assetKind=listing.assetKind;(uint256 fee,uint256 sellerProceeds)=quoteFee(price);listing.status=ListingStatus.SOLD;_releaseListing(listingId,listing);if(paymentToken==address(0)){if(msg.value!=price)revert WrongNativeValue(msg.value,price);_payETH(seller,sellerProceeds,fee);}else{if(msg.value!=0)revert UnexpectedNativeValue();_payERC20(IERC20(paymentToken),msg.sender,seller,price,sellerProceeds,fee);}address asset=assetAddress(assetKind);if(assetKind==AssetKind.SEED){IERC1155(asset).safeTransferFrom(seller,msg.sender,SEED_TOKEN_ID,quantity,"");}else{IERC721(asset).safeTransferFrom(seller,msg.sender,tokenId);}emit ListingPurchased(listingId,seller,msg.sender,assetKind,tokenId,quantity,paymentToken,price,fee);}
    function assetAddress(AssetKind assetKind) public pure returns(address){if(assetKind==AssetKind.SEED)return SEED;if(assetKind==AssetKind.OLD_LORE_LAND)return OLD_LORE_LAND;return CANONICAL_LORE_LAND;}
    function isSupportedPayment(address token) public pure returns(bool){return token==address(0)||token==USDC||token==TOBY;}
    function quoteFee(uint256 price) public pure returns(uint256 fee,uint256 sellerProceeds){fee=(price*FEE_BPS)/BPS_DENOMINATOR;sellerProceeds=price-fee;}
    function seedCapacity(address seller) external view returns(uint256 balance,uint256 reserved,uint256 available){balance=IERC1155(SEED).balanceOf(seller,SEED_TOKEN_ID);reserved=reservedSeeds[seller];if(balance>reserved)available=balance-reserved;}
    function isListingExecutable(uint256 listingId) external view returns(bool){Listing storage listing=listings[listingId];if(listing.status!=ListingStatus.ACTIVE)return false;if(listing.expiresAt!=0&&block.timestamp>listing.expiresAt)return false;if(listing.assetKind==AssetKind.SEED){IERC1155 seed=IERC1155(SEED);if(seed.balanceOf(listing.seller,SEED_TOKEN_ID)<listing.quantity)return false;return seed.isApprovedForAll(listing.seller,address(this));}IERC721 nft=IERC721(assetAddress(listing.assetKind));try nft.ownerOf(listing.tokenId) returns(address owner_){if(owner_!=listing.seller)return false;}catch{return false;}try nft.getApproved(listing.tokenId) returns(address approved){return approved==address(this);}catch{return false;}}
    function proposeFeeRecipient(address newRecipient) external {if(msg.sender!=feeRecipient)revert NotFeeRecipient();if(newRecipient==address(0)||newRecipient==address(this)||newRecipient==feeRecipient)revert InvalidFeeRecipient();pendingFeeRecipient=newRecipient;emit FeeRecipientProposed(feeRecipient,newRecipient);}
    function acceptFeeRecipient() external {if(pendingFeeRecipient==address(0)||msg.sender!=pendingFeeRecipient)revert NotPendingFeeRecipient();address previous=feeRecipient;feeRecipient=pendingFeeRecipient;pendingFeeRecipient=address(0);emit FeeRecipientChanged(previous,feeRecipient);}
    function cancelFeeRecipientTransfer() external {if(msg.sender!=feeRecipient)revert NotFeeRecipient();address cancelled=pendingFeeRecipient;pendingFeeRecipient=address(0);emit FeeRecipientProposalCancelled(feeRecipient,cancelled);}
    function _validateTerms(address paymentToken,uint256 price,uint64 expiresAt) internal view {if(price==0)revert ZeroPrice();if(!isSupportedPayment(paymentToken))revert UnsupportedPaymentToken(paymentToken);if(expiresAt!=0&&expiresAt<=block.timestamp)revert InvalidExpiry();}
    function _requireActive(Listing storage listing) internal view {if(listing.status==ListingStatus.NONE)revert InvalidListing();if(listing.status!=ListingStatus.ACTIVE)revert ListingNotActive();}
    function _validateNewSeedListing(address seller,uint256 tokenId,uint256 quantity) internal view {if(tokenId!=SEED_TOKEN_ID)revert InvalidSeedTokenId(tokenId);if(quantity==0)revert ZeroQuantity();IERC1155 seed=IERC1155(SEED);uint256 balance=seed.balanceOf(seller,SEED_TOKEN_ID);uint256 reserved=reservedSeeds[seller];uint256 available;if(balance>reserved)available=balance-reserved;if(quantity>available)revert InsufficientSeeds(available,quantity);if(!seed.isApprovedForAll(seller,address(this)))revert MarketplaceNotApproved();}
    function _validateLand(address asset,uint256 tokenId,uint256 quantity,address seller) internal view {if(quantity!=1)revert InvalidERC721Quantity(quantity);IERC721 nft=IERC721(asset);address owner_;try nft.ownerOf(tokenId) returns(address currentOwner){owner_=currentOwner;}catch{revert AssetNotOwned();}if(owner_!=seller)revert AssetNotOwned();address approved;try nft.getApproved(tokenId) returns(address approved_){approved=approved_;}catch{revert MarketplaceNotApproved();}if(approved!=address(this))revert MarketplaceNotApproved();}
    function _validateListingAsset(Listing storage listing) internal view {if(listing.assetKind==AssetKind.SEED){IERC1155 seed=IERC1155(SEED);if(seed.balanceOf(listing.seller,SEED_TOKEN_ID)<listing.quantity)revert AssetNotOwned();if(!seed.isApprovedForAll(listing.seller,address(this)))revert MarketplaceNotApproved();return;}_validateLand(assetAddress(listing.assetKind),listing.tokenId,1,listing.seller);}
    function _clearStaleLandListing(address asset,uint256 tokenId) internal {uint256 listingId=activeLandListing[asset][tokenId];if(listingId==0)return;Listing storage oldListing=listings[listingId];if(oldListing.status!=ListingStatus.ACTIVE){delete activeLandListing[asset][tokenId];return;}if(oldListing.expiresAt!=0&&block.timestamp>oldListing.expiresAt){oldListing.status=ListingStatus.CANCELLED;delete activeLandListing[asset][tokenId];return;}address currentOwner;try IERC721(asset).ownerOf(tokenId) returns(address owner_){currentOwner=owner_;}catch{currentOwner=address(0);}if(currentOwner!=oldListing.seller){oldListing.status=ListingStatus.CANCELLED;delete activeLandListing[asset][tokenId];return;}revert ERC721AlreadyListed(listingId);}
    function _releaseListing(uint256 listingId,Listing storage listing) internal {if(listing.assetKind==AssetKind.SEED){reservedSeeds[listing.seller]-=listing.quantity;return;}address asset=assetAddress(listing.assetKind);if(activeLandListing[asset][listing.tokenId]==listingId)delete activeLandListing[asset][listing.tokenId];}
    function _payETH(address seller,uint256 proceeds,uint256 fee) internal {if(seller==feeRecipient){_sendETH(seller,proceeds+fee);return;}if(proceeds!=0)_sendETH(seller,proceeds);if(fee!=0)_sendETH(feeRecipient,fee);}
    function _sendETH(address recipient,uint256 amount) internal {(bool success,)=payable(recipient).call{value:amount}("");if(!success)revert NativeTransferFailed(recipient);}
    function _payERC20(IERC20 token,address buyer,address seller,uint256 price,uint256 proceeds,uint256 fee) internal {uint256 balanceBefore=token.balanceOf(address(this));token.safeTransferFrom(buyer,address(this),price);uint256 balanceAfter=token.balanceOf(address(this));if(balanceAfter<balanceBefore||balanceAfter-balanceBefore!=price)revert InexactERC20Payment();if(seller==feeRecipient){token.safeTransfer(seller,price);}else{if(proceeds!=0)token.safeTransfer(seller,proceeds);if(fee!=0)token.safeTransfer(feeRecipient,fee);}if(token.balanceOf(address(this))!=balanceBefore)revert InexactERC20Payment();}
    function _requireContract(address target) internal view {if(target.code.length==0)revert MissingContract(target);}
}
