'use client';
import {useEffect,useMemo,useState} from 'react';
import {useAccount,useConnect,usePublicClient,useWalletClient} from 'wagmi';
import {injected} from 'wagmi/connectors';
import {base} from 'wagmi/chains';
import {Address,encodeAbiParameters,encodeDeployData,getAddress,isAddress} from 'viem';
import {indexioV3GovernanceConfigAbi,indexioV3GovernanceConfigBytecode,indexioV3SafetyControllerAbi,indexioV3SafetyControllerBytecode,indexioV3FactoryAbi,indexioV3FactoryBytecode,indexioV3VaultDeployerAbi,indexioV3VaultDeployerBytecode,indexioV3ExecutionRouterAbi,indexioV3ExecutionRouterBytecode} from '../lib/indexio-v3.generated';
const REGISTRY=getAddress('0x5C4791e3B752d9b084E8FD76932E82C2031f15c1');const USDC=getAddress('0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913');
type Kind='governanceConfig'|'safetyController'|'factory'|'vaultDeployer'|'executionRouter';const ORDER:Kind[]=['governanceConfig','safetyController','factory','vaultDeployer','executionRouter'];const LABEL:Record<Kind,string>={governanceConfig:'Governance Safety Config',safetyController:'Emergency Safety Controller',factory:'Indexio V3 Factory',vaultDeployer:'Permissionless Vault Deployer',executionRouter:'Execution Router'};const KEY='indexio-v3-deployment-base';
export function IndexioV3Deployer(){const {address,chainId,isConnected}=useAccount();const {connectAsync}=useConnect();const pc=usePublicClient({chainId:base.id});const {data:wc}=useWalletClient({chainId:base.id});const [owner,setOwner]=useState('');const [treasury,setTreasury]=useState('');const [a,setA]=useState<Partial<Record<Kind,Address>>>({});const [status,setStatus]=useState<Partial<Record<Kind,string>>>({});const [busy,setBusy]=useState<string|null>(null);const [msg,setMsg]=useState('');const [err,setErr]=useState('');
useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setA(JSON.parse(x));}catch{}},[]);useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(a));},[a]);useEffect(()=>{if(address&&!owner)setOwner(address);},[address]);
const ownerAddr=useMemo(()=>isAddress(owner)?getAddress(owner):null,[owner]);const treasuryAddr=useMemo(()=>isAddress(treasury)?getAddress(treasury):null,[treasury]);
function artifact(k:Kind){if(k==='governanceConfig')return{abi:indexioV3GovernanceConfigAbi,bytecode:indexioV3GovernanceConfigBytecode,args:[] as readonly unknown[]};if(k==='safetyController'){if(!ownerAddr)throw Error('Enter guardian/owner.');return{abi:indexioV3SafetyControllerAbi,bytecode:indexioV3SafetyControllerBytecode,args:[ownerAddr] as const};}if(k==='factory'){if(!ownerAddr||!treasuryAddr||!a.safetyController)throw Error('Owner, treasury and Safety Controller required.');return{abi:indexioV3FactoryAbi,bytecode:indexioV3FactoryBytecode,args:[ownerAddr,REGISTRY,USDC,treasuryAddr,a.safetyController] as const};}if(k==='vaultDeployer')return{abi:indexioV3VaultDeployerAbi,bytecode:indexioV3VaultDeployerBytecode,args:[] as readonly unknown[]};if(!ownerAddr||!a.factory)throw Error('Owner and Factory required.');return{abi:indexioV3ExecutionRouterAbi,bytecode:indexioV3ExecutionRouterBytecode,args:[ownerAddr,a.factory] as const};}
function ctor(k:Kind){const args=artifact(k).args as readonly Address[];return args.length?encodeAbiParameters(args.map(()=>({type:'address'})) as any,args as any):'0x';}
async function refresh(k:Kind,addr?:Address){const x=addr||a[k];if(!x||!pc)throw Error('Address/client missing.');const code=await pc.getBytecode({address:x});if(!code||code==='0x')throw Error('No bytecode found after deployment.');setStatus(s=>({...s,[k]:'Bytecode confirmed ✓'}));return true;}
async function verify(k:Kind,addr?:Address){const x=addr||a[k];if(!x)throw Error('No address.');setStatus(s=>({...s,[k]:'Verifying…'}));const r=await fetch('/api/blockscout/verify-indexio-v3',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:k,address:x,constructorArguments:ctor(k)})});const j=await r.json();if(!r.ok)throw Error(j.error||'Verification failed');setStatus(s=>({...s,[k]:j.verified?'Verified ✓':'Verification submitted — refresh again'}));return !!j.verified;}
async function deploy(k:Kind){setErr('');setMsg('');setBusy(k);try{if(!pc||!wc||!address||chainId!==base.id)throw Error('Connect the deployment wallet on Base.');const i=ORDER.indexOf(k);if(i>0&&!a[ORDER[i-1]])throw Error(`Finish ${LABEL[ORDER[i-1]]} first.`);const ar=artifact(k);await pc.estimateGas({account:address,data:encodeDeployData({abi:ar.abi as any,bytecode:ar.bytecode,args:ar.args as any})});const h=await wc.deployContract({account:address,chain:base,abi:ar.abi as any,bytecode:ar.bytecode,args:ar.args as any});setStatus(s=>({...s,[k]:'Waiting for receipt…'}));const receipt=await pc.waitForTransactionReceipt({hash:h});if(receipt.status!=='success'||!receipt.contractAddress)throw Error('Deployment reverted.');const x=getAddress(receipt.contractAddress);setA(v=>({...v,[k]:x}));await refresh(k,x);try{await verify(k,x);}catch(e){setStatus(s=>({...s,[k]:'Deployed + bytecode confirmed; verification can be retried'}));}setMsg(`${LABEL[k]} is deployed and refreshed onchain. You can safely continue.`);}catch(e){setErr(e instanceof Error?e.message:'Deployment failed');}finally{setBusy(null);}}
async function recheck(k:Kind){setBusy(`refresh-${k}`);setErr('');try{await refresh(k);await verify(k);setMsg(`${LABEL[k]} refreshed successfully.`);}catch(e){setErr(e instanceof Error?e.message:'Refresh failed');}finally{setBusy(null);}}
function clear(){if(confirm('Clear saved V3 deployment addresses from this browser? This does not affect contracts onchain.')){setA({});setStatus({});localStorage.removeItem(KEY);}}
return <main className="deployerShell"><header><p className="eyebrow">INDEXIO · BASE · V3.0</p><h1>V3 Guided Deployer</h1><p>Deploy → receipt → bytecode refresh → Blockscout verification → next contract. No deployment waiting periods and no vault activation phase.</p></header>{!isConnected?<button className="primary" onClick={()=>connectAsync({connector:injected(),chainId:base.id})}>Connect deployment wallet</button>:null}<section className="card"><h2>Deployment settings</h2><label>Protocol owner / emergency guardian<input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="0x…"/></label><label>Indexio fee treasury (receives mandatory 1%)<input value={treasury} onChange={e=>setTreasury(e.target.value)} placeholder="0x…"/></label><div className="contractBox"><span>REUSED ASSET REGISTRY</span><strong>{REGISTRY}</strong></div><div className="contractBox"><span>BASE USDC</span><strong>{USDC}</strong></div></section>{ORDER.map((k,i)=>{const unlocked=i===0||!!a[ORDER[i-1]];return <section className="card" key={k}><div className="stepHead"><div className="stepNo">{String(i+1).padStart(2,'0')}</div><div><h2>{LABEL[k]}</h2><p>{a[k]?a[k]:'Ready for deployment'}</p></div></div>{a[k]?<><div className="contractBox"><span>ONCHAIN ADDRESS</span><strong>{a[k]}</strong></div><button className="primary" disabled={!!busy} onClick={()=>recheck(k)}>Refresh + verify again</button><a className="linkButton" target="_blank" rel="noreferrer" href={`https://base.blockscout.com/address/${a[k]}`}>Open on Blockscout</a></>:<button className="primary" disabled={!unlocked||!!busy} onClick={()=>deploy(k)}>{busy===k?'Deploying + refreshing…':`Deploy ${LABEL[k]}`}</button>}<p>{status[k]||''}</p></section>})}{msg&&<div className="notice">{msg}</div>}{err&&<div className="errorBox">{err}</div>}<section className="card"><h2>Deployment complete means usable</h2><p>V3 has no bootstrap finalization, per-vault router activation, or deployment timelock. Governance exit windows apply only to later material shareholder-approved changes.</p><button onClick={clear}>Clear saved browser state</button></section></main>}
