'use client';
import {useState} from 'react';
const USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const PATIENCE='0x6D96f18F00B815B2109A3766E79F6A7aD7785624';
type Route={path:string[],pairs:string[],indicativeOut:string,hops:number,compatible:boolean};
type Result={error?:string,router?:string,dexRouter?:string,factory?:string,routes?:Route[],warning?:string,model?:string};
export function IndexioAutoRouteDiscovery(){const [adapter,setAdapter]=useState('');const [tokenIn,setTokenIn]=useState(USDC);const [tokenOut,setTokenOut]=useState(PATIENCE);const [amountIn,setAmountIn]=useState('1000000');const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);
async function discover(){setBusy(true);setResult(null);try{const response=await fetch('/api/indexio/v3/auto-route',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({adapter,tokenIn,tokenOut,amountIn})});setResult(await response.json());}catch(e){setResult({error:String(e)});}finally{setBusy(false);}}
const field=(title:string,value:string,change:(x:string)=>void)=><label style={{display:'grid',gap:4}}>{title}<input value={value} onChange={e=>change(e.target.value)} style={{padding:10,border:'1px solid #888',borderRadius:6,width:'100%'}}/></label>;
return <section style={{border:'1px solid #64748b',padding:18,borderRadius:12,display:'grid',gap:12,marginTop:20}}><h2>Automatic V2 pool discovery (V3.3.11)</h2><p>Searches direct, one-intermediate and two-intermediate paths using the factory linked to your deployed fixed router. No owner route approvals.</p>{field('Deployed fixed adapter address',adapter,setAdapter)}{field('Input token',tokenIn,setTokenIn)}{field('Output token',tokenOut,setTokenOut)}{field('Input amount (raw base units)',amountIn,setAmountIn)}<button type="button" disabled={busy} onClick={discover} style={{padding:12,borderRadius:8,background:'#2563eb',color:'white'}}>{busy?'Discovering…':'Discover compatible pools'}</button>{result?.error&&<p role="alert">{result.error}</p>}{result?.routes&&<><p>Found {result.routes.length} candidate paths. Estimates use {result.model}.</p>{result.routes.map((r,i)=><div key={i} style={{padding:12,border:'1px solid #64748b',borderRadius:8}}><strong>Route {i+1} — {r.hops} hops</strong><div style={{overflowWrap:'anywhere'}}>Path: {r.path.join(' → ')}</div><div>Indicative output (raw units): {r.indicativeOut}</div><div>Adapter structure: {r.compatible?'Compatible':'Incompatible'}</div><small>Pools: {r.pairs.join(', ')}</small></div>)}</>}{result?.warning&&<p style={{fontSize:13}}><strong>Not an executable quote:</strong> {result.warning}</p>}</section>;
}
