'use client';
import {useState} from 'react';
const USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
export function IndexioRouteTestConsole(){
 const [adapter,setAdapter]=useState('');const [fromAddress,setFromAddress]=useState('');const [fromToken,setFromToken]=useState(USDC);const [toToken,setToToken]=useState('0x6D96f18F00B815B2109A3766E79F6A7aD7785624');const [amount,setAmount]=useState('1000000');const [slippage,setSlippage]=useState('500');const [quote,setQuote]=useState<any>(null);const [checks,setChecks]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function test(){setBusy(true);setError('');setQuote(null);setChecks(null);try{
 const r=await fetch('/api/lifi/route',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fromAddress,fromToken,toToken,fromAmount:amount,slippageBps:Number(slippage)})});const q=await r.json();if(!r.ok)throw Error(q.error||'Quote unavailable');setQuote(q);
 if(adapter){const t=await fetch('/api/indexio/v3/route-test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({adapter,target:q.target,spender:q.spender,selector:q.selector})});const x=await t.json();if(!t.ok)throw Error(x.error||'Adapter inspection failed');setChecks(x);}
 }catch(e){setError(e instanceof Error?e.message:'Test failed');}finally{setBusy(false);}}
 const field=(label:string,value:string,set:(s:string)=>void)=><label style={{display:'grid',gap:5,fontSize:13}}>{label}<input value={value} onChange={e=>set(e.target.value)} style={{padding:10,borderRadius:8,border:'1px solid #64748b',background:'transparent',color:'inherit',width:'100%'}} /></label>;
 return <section style={{border:'1px solid #64748b',borderRadius:14,padding:20,margin:'20px 0',display:'grid',gap:14}}><h2 style={{fontSize:20,fontWeight:700}}>LI.FI route test console (Base)</h2><p style={{fontSize:13,opacity:.8}}>Read-only: discover a live quote and check a deployed V3.3.9 adapter’s route permissions. Does not move funds or approve infrastructure.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{field('Deployed LI.FI adapter (optional)',adapter,setAdapter)}{field('Quote sender / adapter address',fromAddress,setFromAddress)}{field('Input token',fromToken,setFromToken)}{field('Output token',toToken,setToToken)}{field('Input amount (raw units)',amount,setAmount)}{field('Slippage (basis points, 10–3000)',slippage,setSlippage)}</div><button onClick={test} disabled={busy} style={{background:'#2563eb',color:'white',padding:12,borderRadius:9,fontWeight:700}}>{busy?'Checking…':'Find route and check permissions'}</button>{error&&<p role="alert" style={{color:'#fb7185'}}>{error}</p>}{quote&&<div style={{fontSize:13,overflowWrap:'anywhere'}}><strong>LI.FI discovery:</strong><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify({tool:quote.tool,target:quote.target,spender:quote.spender,selector:quote.selector,toAmount:quote.toAmount,toAmountMin:quote.toAmountMin},null,2)}</pre></div>}{checks&&<div style={{fontSize:13}}><strong>Onchain adapter permissions:</strong><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(checks.checks,null,2)}</pre><p>{checks.checks?.executable?'Permissions present. Execution remains unverified.':'Route is NOT authorized by this adapter.'}</p></div>}<p style={{fontSize:12,opacity:.8}}>Fee-on-transfer tokens may have multiple dynamic taxes. A quote or green permission check does not establish successful execution or net proceeds. Use a fork or tiny controlled transaction before production.</p></section>;
}
