'use client';
import {useState} from 'react';
const USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const PATIENCE='0x6D96f18F00B815B2109A3766E79F6A7aD7785624';
export function IndexioFixedRouteSimulation(){
 const [adapter,setAdapter]=useState(''),[input,setInput]=useState(USDC),[output,setOutput]=useState(PATIENCE),[path,setPath]=useState(`${USDC},${PATIENCE}`),[recipient,setRecipient]=useState(''),[amount,setAmount]=useState('1000000'),[min,setMin]=useState('1'),[busy,setBusy]=useState(false),[result,setResult]=useState<Record<string,unknown>|null>(null);
 const field=(label:string,value:string,set:(v:string)=>void)=><label style={{display:'grid',gap:4}}>{label}<input style={{padding:10,border:'1px solid #888',borderRadius:6,width:'100%'}} value={value} onChange={e=>set(e.target.value)}/></label>;
 async function test(){setBusy(true);setResult(null);try{const response=await fetch('/api/indexio/v3/simulate-fixed-route',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({adapter,tokenIn:input,tokenOut:output,path:path.split(',').map(x=>x.trim()),recipient,amountIn:amount,minOut:min})});setResult(await response.json());}catch(e){setResult({error:String(e)});}finally{setBusy(false);}}
 return <section style={{border:'1px solid #64748b',borderRadius:12,padding:18,marginTop:20,display:'grid',gap:12}}><h2>V3.3.12 — Fixed adapter read-only simulation</h2><p>Checks adapter compatibility, router approval, funding, and attempts a real-state Base eth_call. No wallet signature or transaction is sent. Paste a discovered path, separated by commas.</p>{field('Deployed fixed adapter',adapter,setAdapter)}{field('Token in',input,setInput)}{field('Token out',output,setOutput)}{field('Path addresses, comma-separated',path,setPath)}{field('Recipient address',recipient,setRecipient)}{field('Amount in (raw units)',amount,setAmount)}{field('Minimum net output (raw units; never use indicative reserve quotes)',min,setMin)}<button type="button" onClick={test} disabled={busy} style={{padding:12,borderRadius:8,background:'#2563eb',color:'white'}}>{busy?'Simulating…':'Run read-only simulation'}</button>{result&&<div style={{padding:12,border:'1px solid #64748b',borderRadius:8,overflowWrap:'anywhere'}}><strong>{result.error?'Error':result.simulated?'eth_call succeeded':result.compatible?'Compatible path — execution not proven':'Incompatible path'}</strong><pre style={{whiteSpace:'pre-wrap',fontSize:12}}>{JSON.stringify(result,null,2)}</pre></div>}</section>;
}
