import fs from 'node:fs';
import path from 'node:path';
import solc from 'solc';

const root = process.cwd();
const entrypoints = [
  'contracts/indexio/IndexioAssetRegistry.sol',
  'contracts/indexio/IndexioFactory.sol',
  'contracts/indexio/IndexioExecutionRouter.sol',
  'contracts/indexio/IndexioRebalanceRouter.sol',
];

const importPattern = /import\s+(?:[^"']*?from\s+)?["']([^"']+)["']\s*;/g;
const sources = {};

function resolveImport(fromKey, request) {
  if (request.startsWith('@')) return request;
  if (request.startsWith('.')) return path.posix.normalize(path.posix.join(path.posix.dirname(fromKey), request));
  return request;
}

function diskPathFor(sourceKey) {
  if (sourceKey.startsWith('@openzeppelin/')) return path.join(root, 'node_modules', sourceKey);
  return path.join(root, sourceKey);
}

function addSource(sourceKey) {
  if (sources[sourceKey]) return;
  const diskPath = diskPathFor(sourceKey);
  if (!fs.existsSync(diskPath)) throw new Error(`Indexio compiler could not resolve ${sourceKey} at ${diskPath}`);
  const content = fs.readFileSync(diskPath, 'utf8');
  sources[sourceKey] = { content };

  for (const match of content.matchAll(importPattern)) {
    addSource(resolveImport(sourceKey, match[1]));
  }
}

for (const entry of entrypoints) addSource(entry);

const input = {
  language: 'Solidity',
  sources,
  settings: {
    optimizer: { enabled: true, runs: 500 },
    viaIR: true,
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object', 'metadata'],
      },
    },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const diagnostics = output.errors || [];
for (const diagnostic of diagnostics) {
  const line = diagnostic.formattedMessage || diagnostic.message;
  if (diagnostic.severity === 'error') console.error(line);
  else console.warn(line);
}
if (diagnostics.some((x) => x.severity === 'error')) process.exit(1);

const targets = [
  ['assetRegistry', 'contracts/indexio/IndexioAssetRegistry.sol', 'IndexioAssetRegistry'],
  ['factory', 'contracts/indexio/IndexioFactory.sol', 'IndexioFactory'],
  ['executionRouter', 'contracts/indexio/IndexioExecutionRouter.sol', 'IndexioExecutionRouter'],
  ['rebalanceRouter', 'contracts/indexio/IndexioRebalanceRouter.sol', 'IndexioRebalanceRouter'],
];

function artifact(source, name) {
  const c = output.contracts?.[source]?.[name];
  if (!c?.abi || !c?.evm?.bytecode?.object) throw new Error(`Missing compiled artifact ${source}:${name}`);
  return {
    abi: c.abi,
    bytecode: `0x${c.evm.bytecode.object}`,
    creationBytes: c.evm.bytecode.object.length / 2,
  };
}

const artifacts = Object.fromEntries(targets.map(([key, source, name]) => [key, artifact(source, name)]));
const compilerVersion = solc.version();
const generated = `// AUTO-GENERATED by scripts/compile-indexio.mjs. Do not edit.\n` +
  `export const indexioCompilerVersion = ${JSON.stringify(compilerVersion)} as const;\n` +
  targets.map(([key]) => {
    const a = artifacts[key];
    const prefix = `indexio${key[0].toUpperCase()}${key.slice(1)}`;
    return `export const ${prefix}Abi = ${JSON.stringify(a.abi)} as const;\nexport const ${prefix}Bytecode = ${JSON.stringify(a.bytecode)} as \`0x\${string}\`;`;
  }).join('\n') + '\n';

const verificationInput = {
  ...input,
  settings: {
    ...input.settings,
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode', 'evm.deployedBytecode', 'metadata'] } },
  },
};
const verification = `// AUTO-GENERATED by scripts/compile-indexio.mjs. Do not edit.\n` +
  `export const indexioStandardJsonInput = ${JSON.stringify(JSON.stringify(verificationInput))} as const;\n`;

fs.mkdirSync(path.join(root, 'lib'), { recursive: true });
fs.writeFileSync(path.join(root, 'lib', 'indexio.generated.ts'), generated);
fs.writeFileSync(path.join(root, 'lib', 'indexio-verification.generated.ts'), verification);

for (const [key] of targets) console.log(`${key}: ${artifacts[key].creationBytes} creation bytes`);
console.log(`Indexio compiler: ${compilerVersion}`);
